# Generated by Django 6.0.7 on 2026-07-17 10:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_alter_org_default_country"),
        ("leads", "0013_lead_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("USD", "USD, Dollar"), ("TOM", "TOM, Toman")],
                max_length=3,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.CreateModel(
            name="InteractionLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("Lead", "Lead"),
                            ("Contact", "Contact"),
                            ("Account", "Account"),
                            ("Opportunity", "Opportunity"),
                        ],
                        help_text="Type of entity this interaction belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        help_text="UUID of the entity this interaction belongs to"
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "تماس تلفنی"),
                            ("email", "ایمیل"),
                            ("meeting", "جلسه"),
                            ("note", "یادداشت"),
                        ],
                        help_text="Type of interaction",
                        max_length=20,
                    ),
                ),
                (
                    "interaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time of the interaction",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short summary/subject",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full notes/conversation details",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "انجام شد"),
                            ("no_answer", "پاسخی نداد"),
                            ("follow_up_required", "نیاز به پیگیری مجدد"),
                            ("not_interested", "عدم علاقه"),
                            ("left_voicemail", "پیغام گذاشته شد"),
                            ("scheduled", "زمان\u200cبندی شد"),
                        ],
                        help_text="Outcome of the interaction",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled next follow-up date/time",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_logs",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction Log",
                "verbose_name_plural": "Interaction Logs",
                "db_table": "interaction_log",
                "ordering": ("-interaction_date",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="interaction_entity__a538ae_idx",
                    ),
                    models.Index(
                        fields=["org", "follow_up_date"],
                        name="interaction_org_id_865fb0_idx",
                    ),
                    models.Index(
                        fields=["org", "interaction_date"],
                        name="interaction_org_id_818bfb_idx",
                    ),
                ],
            },
        ),
    ]
