# Generated by Django 6.0.5 on 2026-08-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_estimate_currency_alter_invoice_currency_and_more'),
        ('leads', '0014_alter_lead_currency_interactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product associated with this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='invoices.product'),
        ),
    ]
