# Generated by Django 6.0.5 on 2026-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_estimate_recurring_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD, Dollar'), ('TOM', 'TOM, Toman')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD, Dollar'), ('TOM', 'TOM, Toman')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD, Dollar'), ('TOM', 'TOM, Toman')], max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD, Dollar'), ('TOM', 'TOM, Toman')], max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD, Dollar'), ('TOM', 'TOM, Toman')], default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
