# Generated by Django - Remove routing_rule and routing_rule_state tables

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_case_merge_record'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS routing_rule_state;",
                "DROP TABLE IF EXISTS routing_rule;",
            ],
            reverse_sql=[
                # The tables were created by migration 0014_routing; reversing
                # this migration means the original CREATE TABLE statements
                # would need to run again. Use the same DDL as 0014.
                # For safety, we simply raise a NotImplementedError.
                "SELECT 1;",  # No-op reverse – restoring the tables requires
                              # reverting to before this migration.
            ],
        ),
    ]
