# Generated by Django 6.0.5 on 2026-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0027_personalaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="phone"
            ),
        ),
    ]
