# Generated by Django 6.0.5 on 2026-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0028_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="", max_length=20, unique=True, verbose_name="phone"
            ),
        ),
    ]
