# Generated by Django 6.0.5 on 2026-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0029_alter_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="invoices_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="org",
            name="opportunities_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="phone"),
        ),
    ]
