# Generated by Django 6.0.7 on 2026-07-17 06:00

from django.db import migrations, models

# Currencies that were removed — any record using these will be migrated to TOM
_REMOVED_CURRENCIES = [
    "EUR", "GBP", "INR", "CAD", "AUD", "JPY", "CNY",
    "CHF", "SGD", "AED", "BRL", "MXN",
]

_KEPT_CURRENCIES = ["USD", "TOM"]


def migrate_org_currency(apps, schema_editor):
    """Update Org records using removed currencies to TOM."""
    Org = apps.get_model("common", "Org")
    Org.objects.filter(default_currency__in=_REMOVED_CURRENCIES).update(
        default_currency="TOM"
    )
    # Also fix any blank/null — set to TOM
    Org.objects.filter(
        default_currency__isnull=True
    ).update(default_currency="TOM")
    Org.objects.filter(default_currency__exact="").update(default_currency="TOM")


def migrate_account_currency(apps, schema_editor):
    """Update Account records using removed currencies to TOM."""
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(currency__in=_REMOVED_CURRENCIES).update(
        currency="TOM"
    )


def migrate_lead_currency(apps, schema_editor):
    """Update Lead records using removed currencies to TOM."""
    Lead = apps.get_model("leads", "Lead")
    try:
        Lead.objects.filter(currency__in=_REMOVED_CURRENCIES).update(currency="TOM")
    except Exception:
        pass


def migrate_opportunity_currency(apps, schema_editor):
    """Update Opportunity records using removed currencies to TOM."""
    Opportunity = apps.get_model("opportunity", "Opportunity")
    try:
        Opportunity.objects.filter(currency__in=_REMOVED_CURRENCIES).update(currency="TOM")
    except Exception:
        pass


def migrate_invoice_currency(apps, schema_editor):
    """Update Invoice and related models using removed currencies to TOM."""
    Invoice = apps.get_model("invoices", "Invoice")
    try:
        Invoice.objects.filter(currency__in=_REMOVED_CURRENCIES).update(currency="TOM")
    except Exception:
        pass


def migrate_recurring_invoice_currency(apps, schema_editor):
    """Update RecurringInvoice records using removed currencies to TOM."""
    RecurringInvoice = apps.get_model("invoices", "RecurringInvoice")
    try:
        RecurringInvoice.objects.filter(currency__in=_REMOVED_CURRENCIES).update(currency="TOM")
    except Exception:
        pass


def migrate_estimate_currency(apps, schema_editor):
    """Update Estimate records using removed currencies to TOM."""
    Estimate = apps.get_model("invoices", "Estimate")
    Estimate.objects.filter(currency__in=_REMOVED_CURRENCIES).update(
        currency="TOM"
    )


def migrate_order_currency(apps, schema_editor):
    """Update Order records using removed currencies to TOM."""
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(currency__in=_REMOVED_CURRENCIES).update(
        currency="TOM"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_add_feature_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="default_currency",
            field=models.CharField(
                choices=[("USD", "USD, Dollar"), ("TOM", "TOM, Toman")],
                default="TOM",
                max_length=3,
            ),
        ),
        migrations.RunPython(migrate_org_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_account_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_lead_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_opportunity_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_invoice_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_recurring_invoice_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_estimate_currency, migrations.RunPython.noop),
        migrations.RunPython(migrate_order_currency, migrations.RunPython.noop),
    ]
