# Generated by Django 6.0.5 on 2026-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_alter_org_default_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apisettings",
            name="apikey",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
