# Generated by Django 6.0.7 on 2026-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Progress", "In Progress"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Deferred", "Deferred"),
                ],
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
